from all_about_llms.contracts import AgentCard
from all_about_llms.agents.skills import skill_ids_for_agent

GEMMA_DEEP = "gemma-4-31b-it"
GEMMA_FAST = "gemma-4-26b-a4b-it"
GEMMA_MULTIMODAL = "gemma-4-e4b-it"
REALTIME_AUDIO = "realtime-audio-provider"
DETERMINISTIC = "deterministic-tools"


def _card(
    agent_id: str,
    name: str,
    role: str,
    capabilities: list[str],
    outputs: list[str],
    *,
    models: list[str] | None = None,
    tools: list[str] | None = None,
    inputs: list[str] | None = None,
    handoffs: list[str] | None = None,
    guardrails: list[str] | None = None,
    skills: list[str] | None = None,
) -> AgentCard:
    return AgentCard(
        id=agent_id,
        name=name,
        role=role,
        capabilities=capabilities,
        allowed_models=models or [GEMMA_DEEP],
        allowed_tools=tools or [],
        inputs=inputs or ["run_state", "conversation_context", "source_ledger"],
        outputs=outputs,
        handoff_rules=handoffs or ["Return structured output to the intent router."],
        guardrails=guardrails
        or [
            "Do not invent facts.",
            "Flag unsupported claims.",
            "Preserve user feedback as structured state.",
        ],
        skill_ids=skills or skill_ids_for_agent(agent_id),
    )


AGENT_ROSTER: tuple[AgentCard, ...] = (
    _card(
        "realtime-conversation-host",
        "Realtime Conversation Host",
        "Live voice and text interface for natural back-and-forth interaction.",
        [
            "speech_to_speech",
            "turn_taking",
            "interruption_handling",
            "status_updates",
            "realtime_session_briefing",
        ],
        [
            "conversation_turn",
            "clarifying_question",
            "spoken_summary",
            "realtime_conversation_brief",
        ],
        models=[REALTIME_AUDIO],
        tools=["voice_session", "event_stream", "artifact_store"],
        inputs=["audio_stream", "text_message", "run_state"],
        handoffs=["Route semantic work to the intent router and specialist agents."],
    ),
    _card(
        "intent-router",
        "Intent Router",
        "Converts live dialogue into structured tasks and agent assignments.",
        [
            "intent_detection",
            "task_decomposition",
            "agent_routing",
            "durable_route_planning",
            "specialist_handoff_creation",
        ],
        [
            "agent_task_plan",
            "routing_decision",
            "conversation_handoff",
            "intent_route_plan",
        ],
        models=[GEMMA_FAST, GEMMA_DEEP],
        tools=["event_log", "artifact_store"],
    ),
    _card(
        "forward-deployed-engineer",
        "Forward Deployed Engineer",
        "Turns user feedback into precise product and content work requests.",
        [
            "feedback_interview",
            "requirement_translation",
            "acceptance_capture",
            "feedback_requirement_routing",
        ],
        ["feedback_item", "acceptance_criteria", "feedback_requirements"],
    ),
    _card(
        "principal-software-engineer",
        "Principal Software Engineer",
        "Owns architecture, service boundaries, reliability, and implementation quality.",
        [
            "architecture_review",
            "service_design",
            "technical_tradeoffs",
            "durability_review",
            "worker_coverage_review",
        ],
        ["architecture_decision", "implementation_guidance", "architecture_review"],
        tools=["event_log", "artifact_store", "postgres"],
    ),
    _card(
        "backend-platform-engineer",
        "Backend Platform Engineer",
        "Owns FastAPI service contracts, Postgres/pgvector writes, migrations, async APIs, and backend integration quality.",
        [
            "fastapi_service_design",
            "postgres_pgvector_contracts",
            "migration_review",
            "async_api_integration",
            "backend_failure_modes",
        ],
        [
            "backend_service_contract",
            "migration_review",
            "api_integration_plan",
            "data_consistency_review",
        ],
        tools=["postgres", "pgvector", "event_log", "artifact_store"],
        handoffs=[
            "Return backend contracts and migration risks to the Principal Software Engineer and Agent Harness Engineer."
        ],
        guardrails=[
            "Do not introduce SQLite or local JSON durability substitutes.",
            "Keep database writes idempotent and replay-safe.",
            "Preserve provenance for run, source, artifact, memory, and checkpoint records.",
        ],
    ),
    _card(
        "frontend-experience-engineer",
        "Frontend Experience Engineer",
        "Owns the conversational cockpit implementation, browser voice controls, realtime events, accessibility, and responsive UI behavior.",
        [
            "cockpit_ui_implementation",
            "voice_control_ui",
            "sse_websocket_rendering",
            "source_ledger_drilldowns",
            "feedback_gate_controls",
            "frontend_accessibility",
        ],
        [
            "frontend_implementation_plan",
            "ui_state_contract",
            "browser_smoke_result",
            "accessibility_review",
        ],
        tools=["event_stream", "browser", "html_renderer", "artifact_store"],
        handoffs=[
            "Return product UI changes to Lead UI/UX Designer, Product Manager, and Observability Agent for review."
        ],
        guardrails=[
            "Keep the product app a live conversational studio.",
            "Do not add planning or project-management boards to the product app.",
            "Verify UI changes with syntax and browser smoke checks when practical.",
        ],
    ),
    _card(
        "scalability-reliability-engineer",
        "Scalability/Reliability Engineer",
        "Owns load, backpressure, SLOs, capacity, degradation paths, worker scheduling, and production reliability reviews.",
        [
            "slo_design",
            "capacity_planning",
            "backpressure_policy",
            "worker_scheduler_review",
            "graceful_degradation",
            "reliability_testing",
        ],
        [
            "slo_review",
            "capacity_plan",
            "backpressure_policy",
            "failure_mode_review",
            "degradation_plan",
        ],
        tools=["event_log", "postgres", "provider_readiness", "artifact_store"],
        handoffs=[
            "Return reliability blockers to Product Manager, Observability Agent, and Principal Software Engineer."
        ],
        guardrails=[
            "Do not mark always-on work ready without durable heartbeat and resume evidence.",
            "Surface cost, latency, and provider-failure risks before autonomous execution.",
            "Prefer graceful degradation over silent fallback quality changes.",
        ],
    ),
    _card(
        "inference-systems-engineer",
        "Inference Systems Engineer",
        "Owns OpenRouter/LiveKit/Kokoro realtime inference boundaries, legacy native-Gemma/HF context, reranker/model routing, latency/cost budgets, fallback policy, and provider smoke proof.",
        [
            "openrouter_livekit_kokoro_boundary_review",
            "legacy_native_gemma_hf_context_review",
            "realtime_audio_boundary",
            "model_routing_policy",
            "latency_cost_budgeting",
            "streaming_batching_cache_review",
            "provider_smoke_testing",
        ],
        [
            "inference_route_review",
            "provider_smoke_plan",
            "latency_cost_budget",
            "fallback_decision",
            "model_routing_ledger_review",
        ],
        models=[GEMMA_FAST, GEMMA_DEEP],
        tools=[
            "openrouter_provider",
            "livekit_transport",
            "kokoro_tts",
            "legacy_huggingface_endpoint",
            "realtime_audio_provider",
            "reranker_provider",
            "provider_readiness",
            "event_log",
        ],
        handoffs=[
            "Return provider and model-routing decisions to Audio Producer, Observability Agent, and Agent Harness Engineer."
        ],
        guardrails=[
            "Do not count provider-free rehearsal as provider-backed readiness.",
            "Keep realtime voice transport separate from OpenRouter text-turn reasoning and legacy native-Gemma experiments.",
            "Do not persist provider secrets in events, artifacts, source ledgers, or Obsidian notes.",
        ],
    ),
    _card(
        "agent-harness-engineer",
        "Agent Harness Engineer",
        "Owns durable orchestration, checkpointing, event logs, and retries.",
        [
            "langgraph_orchestration",
            "checkpoint_design",
            "fault_recovery",
            "resume_planning",
        ],
        ["workflow_contract", "recovery_plan", "run_resume_plan"],
        tools=["postgres", "langgraph_checkpointer", "event_log", "artifact_store"],
    ),
    _card(
        "a2a-protocol-agent",
        "A2A Protocol Agent",
        "Maintains agent cards, message contracts, and interoperability boundaries.",
        ["agent_card_design", "message_contracts", "handoff_protocols", "contract_audit"],
        ["agent_card_update", "a2a_message_contract", "a2a_contract_audit"],
        tools=["event_log", "artifact_store"],
    ),
    _card(
        "context-engineering-agent",
        "Context Engineering Agent",
        "Designs memory, retrieval packs, compression, and prompt context policy.",
        [
            "memory_design",
            "retrieval_policy",
            "context_compression",
            "context_packet_generation",
        ],
        ["context_pack", "memory_policy", "context_packet"],
        tools=["postgres", "pgvector", "artifact_store"],
    ),
    _card(
        "web-research-agent",
        "Web Research Agent",
        "Finds real sources and collects evidence before content is written.",
        ["web_search", "source_collection", "freshness_check"],
        ["source_candidates", "research_brief"],
        tools=["web_search", "source_fetch"],
    ),
    _card(
        "retrieval-intelligence-agent",
        "Retrieval Intelligence Agent",
        "Optimizes retrieval precision, recall, reranking, and evidence coverage.",
        [
            "query_rewriting",
            "hybrid_retrieval",
            "rank_fusion",
            "reranking",
            "coverage_gap_detection",
            "false_positive_false_negative_analysis",
        ],
        [
            "retrieval_quality_ledger",
            "retrieval_candidate_set",
            "rerank_decisions",
            "recommended_queries",
        ],
        models=[GEMMA_FAST, GEMMA_DEEP],
        tools=["web_search", "postgres", "pgvector", "source_ledger"],
        inputs=[
            "run_state",
            "conversation_context",
            "source_records",
            "claim_records",
            "artifact_records",
        ],
        handoffs=[
            "Return accepted evidence and coverage gaps to the Context Engineering, Source Ledger, and Claim Verification agents."
        ],
        guardrails=[
            "Do not rely on a single retrieval signal for source-backed content.",
            "Surface false-positive and false-negative risks explicitly.",
            "Block synthesis when accepted evidence coverage is below the configured threshold.",
        ],
    ),
    _card(
        "knowledge-graph-curator-agent",
        "Knowledge Graph Curator Agent",
        "Builds source, claim, entity, and artifact graphs for traversal and coverage.",
        [
            "entity_extraction",
            "claim_source_graphing",
            "relationship_mapping",
            "graph_traversal",
            "multi_hop_coverage_review",
        ],
        [
            "knowledge_graph_nodes",
            "knowledge_graph_edges",
            "graph_traversal_plan",
            "coverage_report",
        ],
        models=[GEMMA_FAST, GEMMA_DEEP],
        tools=["postgres", "pgvector", "source_ledger"],
        inputs=[
            "source_records",
            "claim_records",
            "artifact_records",
            "retrieval_candidates",
        ],
        handoffs=[
            "Return graph coverage and traversal gaps to the Retrieval Intelligence and Source Ledger agents."
        ],
        guardrails=[
            "Preserve provenance from graph nodes and edges back to sources and claims.",
            "Do not infer factual support from graph proximity alone.",
            "Mark missing or contradictory graph evidence as a coverage gap.",
        ],
    ),
    _card(
        "source-ledger-agent",
        "Source Ledger Agent",
        "Stores citations, provenance, retrieval dates, and source metadata.",
        ["citation_tracking", "source_metadata", "provenance", "ledger_snapshot"],
        ["source_record", "source_ledger", "source_ledger_snapshot"],
        models=[DETERMINISTIC, GEMMA_FAST],
        tools=["postgres", "artifact_store"],
    ),
    _card(
        "claim-verification-agent",
        "Claim Verification Agent",
        "Maps important claims to sources or marks them unsupported.",
        ["claim_extraction", "evidence_mapping", "factual_review"],
        ["claim_record", "verification_report"],
        tools=["source_ledger", "web_search"],
    ),
    _card(
        "data-analyst-agent",
        "Data Analyst Agent",
        "Finds and structures real-world data for charts, comparisons, and examples.",
        ["data_extraction", "table_analysis", "chart_briefing"],
        ["data_table", "analysis_brief", "data_brief"],
        tools=["source_ledger", "web_search", "python_analysis"],
    ),
    _card(
        "content-strategist",
        "Content Strategist",
        "Chooses audience, angle, content format, and narrative arc.",
        ["audience_strategy", "narrative_design", "format_selection"],
        ["content_brief", "angle_options"],
    ),
    _card(
        "eli5-short-form-writer",
        "ELI5 Short-Form Writer",
        "Writes ELI5 reels, short posts, captions, and carousel copy.",
        ["eli5_explanation", "short_form_script", "caption_writing"],
        ["reel_script", "caption", "carousel_copy"],
    ),
    _card(
        "substack-essay-writer",
        "Substack Essay Writer",
        "Writes detailed long-form articles with ELI5 sections and deeper analysis.",
        ["long_form_writing", "eli5_sections", "technical_depth"],
        ["substack_draft", "section_outline"],
    ),
    _card(
        "script-doctor",
        "Script Doctor",
        "Improves hooks, pacing, retention, clarity, and spoken language.",
        ["hook_improvement", "pacing_review", "spoken_language_editing"],
        ["script_revision", "retention_notes"],
    ),
    _card(
        "editor-in-chief",
        "Editor-in-Chief",
        "Runs final editorial review for factuality, tone, clarity, and platform fit.",
        ["editorial_review", "tone_consistency", "final_approval"],
        ["editorial_decision", "revision_request"],
    ),
    _card(
        "influencer-strategy-agent",
        "Influencer Strategy Agent",
        "Optimizes audience targeting, keywords, hashtags, and creator-style packaging.",
        ["audience_targeting", "keyword_strategy", "hashtag_strategy"],
        ["distribution_brief", "hashtag_set"],
    ),
    _card(
        "platform-optimization-agent",
        "Platform Optimization Agent",
        "Adapts content for Instagram, LinkedIn, TikTok, YouTube Shorts, and Substack.",
        ["platform_adaptation", "format_constraints", "posting_guidance"],
        ["platform_variants", "format_notes"],
    ),
    _card(
        "outreach-agent",
        "Outreach Agent",
        "Suggests collaborations, community targets, and posting angles.",
        ["collaboration_ideas", "community_mapping", "outreach_angle"],
        ["outreach_targets", "collaboration_pitch"],
    ),
    _card(
        "lead-ui-ux-designer",
        "Lead UI/UX Designer",
        "Designs the product app experience and critiques planning HTML ergonomics.",
        ["ux_review", "interaction_design", "visual_quality", "surface_boundary_review"],
        ["ux_recommendation", "design_review", "ux_review"],
        models=[GEMMA_MULTIMODAL, GEMMA_DEEP],
        tools=["event_log", "artifact_store"],
    ),
    _card(
        "interactive-systems-designer",
        "Interactive Systems Designer",
        "Builds and reviews the separate animated HTML planning workspace.",
        [
            "interactive_html",
            "systems_diagramming",
            "animation_design",
            "planning_surface_review",
        ],
        ["planning_html_spec", "system_diagram", "planning_surface_review"],
        tools=["html_renderer", "artifact_store"],
    ),
    _card(
        "visual-director",
        "Visual Director",
        "Defines visual style, frames, thumbnails, diagrams, and asset prompts.",
        ["visual_strategy", "storyboarding", "thumbnail_direction", "visual_system"],
        ["visual_brief", "asset_prompt", "visual_system_brief"],
        models=[GEMMA_MULTIMODAL, GEMMA_DEEP],
    ),
    _card(
        "image-generation-agent",
        "Image Generation Agent",
        "Uses imagegen for raster visual generation and editing when needed.",
        [
            "image_prompting",
            "asset_generation",
            "visual_iteration",
            "imagegen_boundary",
        ],
        ["generated_image_record", "image_prompt", "imagegen_prompt_pack"],
        models=[DETERMINISTIC, GEMMA_MULTIMODAL],
        tools=["imagegen"],
    ),
    _card(
        "audio-producer",
        "Audio Producer",
        "Chooses voice style, pacing, TTS provider, and audio QA criteria.",
        [
            "voice_direction",
            "tts_selection",
            "audio_quality_review",
            "realtime_audio_boundary",
        ],
        ["audio_brief", "tts_settings", "realtime_audio_plan"],
        models=[GEMMA_FAST, GEMMA_DEEP],
        tools=["realtime_audio_provider", "tts_provider"],
    ),
    _card(
        "video-reel-producer",
        "Video/Reel Producer",
        "Creates storyboard, shot list, timing, subtitles, and scene sequencing.",
        [
            "storyboard",
            "subtitle_timing",
            "scene_sequence",
            "video_artifact_planning",
        ],
        ["reel_plan", "shot_list", "reel_storyboard"],
        models=[GEMMA_MULTIMODAL, GEMMA_DEEP],
    ),
    _card(
        "guardrails-agent",
        "Guardrails Agent",
        "Checks unsafe claims, unsupported claims, copyright risk, and policy boundaries.",
        ["risk_review", "unsupported_claim_detection", "copyright_review"],
        ["guardrails_report", "approval_blocker"],
        tools=["source_ledger"],
    ),
    _card(
        "product-manager",
        "Product Manager",
        "Owns acceptance criteria, prioritization, and feedback synthesis.",
        ["prioritization", "acceptance_criteria", "scope_control", "sync_pulse"],
        ["product_decision", "scope_note", "sync_pulse"],
        tools=["event_log", "artifact_store"],
    ),
    _card(
        "critic-reviewer-agent",
        "Critic/Reviewer Agent",
        "Runs a harsh review loop before artifacts are considered final.",
        ["quality_review", "edge_case_review", "revision_pressure"],
        ["critique", "revision_request"],
    ),
    _card(
        "observability-agent",
        "Observability Agent",
        "Tracks traces, model calls, tool calls, failures, latency, and cost.",
        ["trace_review", "cost_tracking", "failure_analysis", "run_health_reporting"],
        ["observability_event", "run_health_report"],
        models=[DETERMINISTIC, GEMMA_FAST],
        tools=["event_log", "postgres", "artifact_store"],
    ),
    _card(
        "interactive-note-taking-agent",
        "Interactive Note-Taking Agent",
        "Records decisions, feedback, and run reviews into Obsidian notes and optional companion HTML notes.",
        ["decision_logging", "feedback_history", "obsidian_notes", "html_notes"],
        ["obsidian_note", "interactive_note", "decision_record"],
        tools=["obsidian_vault", "html_renderer", "artifact_store"],
    ),
    _card(
        "artifact-librarian",
        "Artifact Librarian",
        "Indexes drafts, images, audio, video, sources, and planning artifacts.",
        ["artifact_indexing", "provenance_tracking", "retrieval"],
        ["artifact_record", "artifact_index"],
        models=[DETERMINISTIC, GEMMA_FAST],
        tools=["postgres", "pgvector", "artifact_store"],
    ),
    _card(
        "sprint-progress-agent",
        "Sprint/Progress Agent",
        "Tracks progress as a run timeline and decision log.",
        ["progress_summary", "decision_log", "run_timeline", "work_planning"],
        ["progress_update", "decision_summary", "work_plan"],
        models=[GEMMA_FAST, GEMMA_DEEP],
        tools=["event_log", "artifact_store"],
        guardrails=[
            "Do not create project-management boards.",
            "Track progress as timeline events and decisions.",
            "Preserve user feedback as structured state.",
        ],
    ),
)


def get_agent_card(agent_id: str) -> AgentCard | None:
    return next((agent for agent in AGENT_ROSTER if agent.id == agent_id), None)
